[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "a6b6a73123c51d64fc30aa1caf34364bacf0f8a5"
os = "macos"

    [[FriBidi.download]]
    sha256 = "082c1322624d7ea3b099f0f5ee6bce4f1cb4a73b0a1268e4289442a0ebe88f52"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.aarch64-apple-darwin.tar.gz"
[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "25cadd996d333a98b1f2886d2bc802e246c8ddd2"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "384ea43176699700812eadf263ab0864863186c3b5f6da0a859532040e6ec710"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.aarch64-linux-gnu.tar.gz"
[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "cc6b2fbe50901742c9f179c1d89839b77f4c4560"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "844f8b49575f59fc66d8993877ced0f81440a91e884a865e1530ffb7723b5c03"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.aarch64-linux-musl.tar.gz"
[[FriBidi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c999da5b577f4ca18128f3039b980cbf09bdab7"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "a22659e850cb14f8468db943567de8d3788c6df993a09347574246250c2f1885"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.armv6l-linux-gnueabihf.tar.gz"
[[FriBidi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd7e41c517f3c4f9445684459fe6863e517f68ae"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "aa2644bb6b7fc67b239bb8d79f67b70ac63c0185f7c472a9170f8a56f38f4dff"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.armv6l-linux-musleabihf.tar.gz"
[[FriBidi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38d44291525d953fd7c78833195aece655b5faec"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "da8233bf45ae6e4ed9c055c7f72b8b1ecf03e699723e143531b694b078828590"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.armv7l-linux-gnueabihf.tar.gz"
[[FriBidi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e6a170a34141303a1beb23fdaa81d8e36663dc4"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "424cee2f27f4a3af8935f5879f01c029357f54403fbc5abb174c5b4ecafd8057"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.armv7l-linux-musleabihf.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "53122b869415e2a29aaff3e0bb73a61301c45a49"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "951e11179185664f3f3eb66a282b55c371d17a49a1a69327e6e9489f2dc4b6af"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.i686-linux-gnu.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "f4cfdeade2c1e006008094045a0095e97d0142b9"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "ab2f4a76a6b92d58513e3101ab302fd542d30ee4ba77766dd37965cc03e4e6cf"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.i686-linux-musl.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "4df56f0af84b721709ab9a1f25c354f76347b796"
os = "windows"

    [[FriBidi.download]]
    sha256 = "163ebce6d9176114c299a571fbac6939208809adca80e9278447b7c0490b5989"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.i686-w64-mingw32.tar.gz"
[[FriBidi]]
arch = "powerpc64le"
git-tree-sha1 = "014bd597ff5f7173f7bdcecd885b460182a91218"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "9108be903d6b30a747b8d0be04d9aab3ffe28fb7d1e875eae4bf94d5fcefa5b8"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.powerpc64le-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "283f882df6f27091e6ecd8ef992ae9fecc7639dd"
os = "macos"

    [[FriBidi.download]]
    sha256 = "3eef49318b68dbfad9252e0422a908f557039e1ba19e3bb2c60ee34a965e2b42"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.x86_64-apple-darwin.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "2ab21f29b30c228bd0e5215585f822730cad5a72"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "4c336cf18e955d6af0030cb0ae1877ca3e2a41e88acfb58be743cfde03bdf778"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.x86_64-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "b4e9aa5031a96d62b7e566c9453c362f7cd994bf"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "5301b96e0dedba8195586b32c7dc9f8d78a0cb692427d5de79b94be5f135865a"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.x86_64-linux-musl.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "01406e3c2f0e74359bc43cf74da842795cc1e702"
os = "freebsd"

    [[FriBidi.download]]
    sha256 = "1d7621597a822785bead5ccd98b21273026ec2930c4b296b405daac0ff3dc29d"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.x86_64-unknown-freebsd.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "4f8287228fc5b62c789ef45496d1df624df912ac"
os = "windows"

    [[FriBidi.download]]
    sha256 = "d2f7e00b254b3431257908a46309b302d2999ef3e8df7ad0aec835dd6f0e405a"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.14+0/FriBidi.v1.0.14.x86_64-w64-mingw32.tar.gz"
